services:
  # -----------------------------------------------------------------
  #  1. Python ML Service
  # -----------------------------------------------------------------
  - type: web
    name: recommender-ml-service
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    rootDir: ./python-ml-service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs

  # -----------------------------------------------------------------
  #  2. Java Backend Service
  # -----------------------------------------------------------------
  - type: web
    name: recommender-backend
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      # Pulls DB credentials directly from the secret group
      - fromGroup: recommender-secrets
      # The static internal URL for the ML service
      - key: ML_SERVICE_URL
        value: http://recommender-ml-service:8000
      # A secure, generated JWT secret
      - key: JWT_SECRET
        generateValue: true

  # -----------------------------------------------------------------
  #  3. Frontend Service 
  # -----------------------------------------------------------------
  - type: web
    name: recommender-frontend
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    rootDir: ./frontend
    dockerfilePath: ./Dockerfile
    envVars:
      # The public, static URL for the backend service
      - key: API_BASE_URL
        value: https://recommender-backend-6ndq.onrender.com