services:
  # The Python ML Service (changed to a Private Service)
  - type: pserv # <-- Changed from 'web'
    name: recommender-ml-service
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./python-ml-service/Dockerfile
    envVars:
      - fromGroup: recommender-secrets

  # The Java Backend Service
  - type: web
    name: recommender-backend
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: recommender-secrets
      - key: ML_SERVICE_URL
        value: http://recommender-ml-service:8000

  # The HTML/CSS/JS Frontend Service
  - type: web
    name: recommender-frontend
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./frontend/Dockerfile