services:
  # -----------------------------------------------------------------
  #  1. Database Service (Represents your external Railway DB)
  # -----------------------------------------------------------------
  - type: pserv
    name: recommender-db
    envVars:
      - fromGroup: recommender-secrets

  # -----------------------------------------------------------------
  #  2. Python ML Service
  # -----------------------------------------------------------------
  - type: web
    name: recommender-ml-service
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    rootDir: ./python-ml-service
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs

  # -----------------------------------------------------------------
  #  3. Java Backend Service
  # -----------------------------------------------------------------
  - type: web
    name: recommender-backend
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${recommender-db.RAILWAY_DB_HOST}:${recommender-db.RAILWAY_DB_PORT}/railway
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: pserv
          name: recommender-db
          envVarKey: RAILWAY_DB_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: pserv
          name: recommender-db
          envVarKey: RAILWAY_DB_PASSWORD
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: recommender-ml-service
          property: url
      - key: JWT_SECRET
        generateValue: true

  # -----------------------------------------------------------------
  #  4. Frontend Service 
  # -----------------------------------------------------------------
  - type: web
    name: recommender-frontend
    plan: free
    runtime: docker
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    # THIS LINE IS THE MOST IMPORTANT ONE FOR THIS FIX
    rootDir: ./frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: recommender-backend
          property: externalUrl