services:
  # The Python ML Service (as a public Web Service)
  - type: web # <-- Changed back to 'web'
    name: recommender-ml-service
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./python-ml-service/Dockerfile
    healthCheckPath: /docs
    envVars:
      - fromGroup: recommender-secrets

  # The Java Backend Service
  - type: web
    name: recommender-backend
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: recommender-secrets
      # The ML_SERVICE_URL is now read from the secrets group

  # The HTML/CSS/JS Frontend Service
  - type: web
    name: recommender-frontend
    runtime: docker
    plan: free
    repo: https://github.com/Samved-Gupta/Research-Paper-Recommendation-System
    dockerfilePath: ./frontend/Dockerfile 